version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: GREMA_APP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tfg-network

  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - API_ORIGIN=http://backend:3001
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - tfg-network

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
      - API_ORIGIN=http://backend:3001
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - tfg-network

volumes:
  pgdata:
  backend_node_modules:
  frontend_node_modules:

networks:
  tfg-network:
    driver: bridge
