name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create .env and deploy to EC2
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" > backend.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> backend.env
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> backend.env
          echo "EMAIL_SERVICE=${{ secrets.EMAIL_SERVICE }}" >> backend.env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> backend.env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> backend.env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> backend.env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> backend.env

          echo "[+] Copying .env to EC2..."
          scp -o StrictHostKeyChecking=no backend.env ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:~/TFG-GISI/backend/.env

          echo "[+] Running deploy.sh remotely..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} 'bash ~/deploy.sh'
